# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  - .jekyll-cache

# 2. Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-include-cache
  - jekyll-feed
  - jemoji

# 3. Gem settings
paginate: 10 # jekyll-paginate > items per page
paginate_path: page:num # jekyll-paginate > blog page
author: aiceru # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  links: # jekyll-seo-tag > social aliases (sameAs)
    - https://github.com/aiceru
markdown: kramdown # Markdown parse settings, CommonMark performs slightly better an others in build time
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 1..3
# commonmark:
# options: ["SMART", "FOOTNOTES"]
# extensions: ["strikethrough", "autolink", "table"]
highlighter: rouge

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Seoul # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: # Needed for Siteleaf
    output: true
    # description: "The moon always lights" # The post list page contens
    feature_image: '/assets/logos/blossom.jpg'

# 6. Jekyll collections settings
defaults:
  - scope:
      path: ''
    values:
      image: '/assets/logos/moon.png' # Default image for sharing

# 7. Site settings
encoding: UTF-8 # Make sure the encoding is right
lang: ko-KR # Set the site language
title: 'MoonLights' # Site name or title, also used in jekyll-seo-tag
logo: 'https://www.gravatar.com/avatar/d78158bd0af0557edb8328a414cfe3b5?s=40' # Site logo, also used in jekyll-seo-tag
description: "Working developer's life with cycling, woodworking, gaming" # Site description and default description, also used in jekyll-seo-tag
url: 'https://aiceru.github.io' # Site url, also used in jekyll-seo-tag
baseurl: ''
repo: 'https://github.com/aiceru/aiceru.github.io'
email: 'aiceru@gmail.com'
disqus: 'moon-light-2' # Blog post comments, uncomment the option and set the site ID from your Disqus account
google_analytics: 'G-MH3J58HP07'
google_analytics_anonymize_ip: 'false'
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: 'https://www.gravatar.com/avatar/d78158bd0af0557edb8328a414cfe3b5?s=16'
  32: 'https://www.gravatar.com/avatar/d78158bd0af0557edb8328a414cfe3b5?s=32'
  96: 'https://www.gravatar.com/avatar/d78158bd0af0557edb8328a414cfe3b5?s=96'
  120: 'https://www.gravatar.com/avatar/d78158bd0af0557edb8328a414cfe3b5?s=120'
  144: 'https://www.gravatar.com/avatar/d78158bd0af0557edb8328a414cfe3b5?s=144'
  180: 'https://www.gravatar.com/avatar/d78158bd0af0557edb8328a414cfe3b5?s=180'
  512: 'https://www.gravatar.com/avatar/d78158bd0af0557edb8328a414cfe3b5?s=512'
  1024: 'https://www.gravatar.com/avatar/d78158bd0af0557edb8328a414cfe3b5?s=1024'

# 9. Site navigation
navigation_header:
  - title: Home
    url: /
  - title: Categories
    url: /categories/
  - title: Tags
    url: /tags/
  - title: Search
    url: /search/
  - title: About
    url: /about/
    #- title: Fork Alembic
    #url: https://github.com/daviddarnes/alembic

navigation_footer:
  - title: MoonLights

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/aiceru
  GitHub: https://github.com/aiceru
  Instagram: https://instagram.com/iceru
  link: https://aiceru.github.io
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: '#1DA1F2'
  Facebook: '#4267B2'
  Linkedin: '#0e76a8'
  Email: true
